// eslint.config.mjs  — ESLint flat config (v9+ / @eslint/js)
// Generated by: npm init @eslint/config
import js from "@eslint/js";
import globals from "globals";

export default [
  // Apply recommended rules as the base
  js.configs.recommended,

  {
    // Lint all JS files in the project
    files: ["**/*.js"],

    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs", // Node.js uses require/module.exports
      globals: {
        ...globals.node, // process, __dirname, require, etc.
        ...globals.jest, // describe, test, expect, beforeEach, etc.
      },
    },

    rules: {
      "no-console": "off", // console.log is fine in a server app
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      eqeqeq: "error", // always === not ==
      curly: "error", // always use braces for blocks
    },
  },

  {
    // Ignore generated / dependency directories
    ignores: ["node_modules/", "coverage/", "playwright-report/"],
  },
];
